liste=[]
elemanlar1=(input("Listenin içine atılacak elemanları girin: "))
elemanlar2=(input("Listenin içine atılacak elemanları girin: "))
elemanlar3=(input("Listenin içine atılacak elemanları girin: "))
elemanlar4=(input("Listenin içine atılacak elemanları girin: "))
elemanlar5=(input("Listenin içine atılacak elemanları girin: "))
elemanlar6=(input("Listenin içine atılacak elemanları girin: "))
elemanlar7=(input("Listenin içine atılacak elemanları girin: "))
elemanlar8=(input("Listenin içine atılacak elemanları girin: "))
elemanlar9=(input("Listenin içine atılacak elemanları girin: "))
elemanlar10=(input("Listenin içine atılacak elemanları girin: "))
liste.append(elemanlar1)
liste.append(elemanlar2)
liste.append(elemanlar3)
liste.append(elemanlar4)
liste.append(elemanlar5)
liste.append(elemanlar6)
liste.append(elemanlar7)
liste.append(elemanlar8)
liste.append(elemanlar9)
liste.append(elemanlar10)
print("Listenin içindekiler:",*liste)    #listenin onundeki yildiz kseli parantez ve virgulu siliyor